service:
  name: serverlesstest
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:  
  - serverless-webpack
  - serverless-offline-lambda
  - serverless-offline
# custom:
#   serverless-offline:
#     port: 3000

provider:
  name: aws
  runtime: nodejs10.x

functions:
  lambda1:
    handler: handler.lambda1
    events:
      - http:
          method: get
          path: lambda1
  lambda2:
    handler: handler.lambda2
    events:
      - http:
          method: post
          path: lambda2
